#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2022
configuration: Release
environment:
  NUGET_TOKEN:
    secure: hA7gNbFhOr/6AilfgIRGHT1A6TzB1+hhxxYmwctD4lDaVgGb+qGeFYV6xJ0wyNTM
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
build_script:
  - ps: .\build.ps1
test: off
